name: rc-testing

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # TODO: Add more OS when we are sure this package can run on those.
        #os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: '3.13-dev'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install numpy astropy --pre
        python -m pip install -e .[test]
    - name: Run tests
      run: pytest
